model: ???
vae: null
tokenizer: null
output_dir: 'output'
project: 'SCAL-SDT'

data:
  resolution: 512
  center_crop: false
  concepts: [ ]

checkpoint:
  filename: '{epoch}-{train_loss:.2f}'
  auto_insert_metric_name: true
  every_n_epochs: 1

trainer:
  accelerator: gpu
  devices: -1
  auto_select_gpus: true
  precision: 16
  move_metrics_to_cpu: true
  log_every_n_steps: 1

batch_size: 1
seed: None

prior_preservation:
  enabled: false
  prior_loss_weight: 1.0

train_text_encoder: false
gradient_checkpointing: false
med_vram: false

aspect_ratio_bucket:
  enabled: false
  debug: false

clip_stop_at_layer: 1
pad_tokens: true

loggers: { }

optimizer:
  name: bitsandbytes.optim.AdamW8bit
  params: ???
  lr_scale:
    enabled: true
    method: 'sqrt'
  lr_scheduler:
    name: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
    params: ???
    warmup:
      enabled: true
      init_lr: 7e-8
      steps: 100
      strategy: 'linear'
